// levels.jsx — chapter and puzzle definitions
// Each chapter has 3-5 puzzles in its pool; replays serve unseen first.

const LEVELS = [
  {
    id: 1,
    title: "The Naming of Things",
    topic: "Variables & Types",
    sigil: "scroll",
    teach: [
      "In Python, names are not boxes — they are labels you tie to values with `=`.",
      "Common types: `int` (whole numbers), `float` (decimals), `str` (text in quotes), `bool` (True/False).",
      "`type(x)` reveals the kind of thing `x` is.",
    ],
    example: `gold = 42\nname = "Aria"\nready = True\nprint(type(gold))   # <class 'int'>`,
    xp: 30, mana: 8,
    puzzles: [
      { id: "v-mcq-1", kind: "mcq",
        prompt: "Which line correctly creates a string variable named `quest`?",
        options: ["quest = adventure", "quest := \"adventure\"", "quest = \"adventure\"", "string quest = \"adventure\""],
        answer: 2,
        hint: "Strings need quotes. Plain `=` is the basic Python assignment." },
      { id: "v-pred-1", kind: "predict",
        prompt: "What does this print?",
        code: `x = 7\ny = \"7\"\nprint(type(x) == type(y))`,
        answer: "False",
        accept: ["false", "False"],
        hint: "One is an int. The other is wearing quotes." },
      { id: "v-fill-1", kind: "fill",
        prompt: "Make `power` equal to half of `level`.",
        code: `level = 20\npower = ___\nprint(power)  # should print 10.0`,
        blanks: ["level / 2"],
        accept: [["level/2", "level / 2"]],
        hint: "`/` always returns a float in Python 3." },
      { id: "v-bug-1", kind: "bug",
        prompt: "One line is broken. Click the bad line.",
        lines: [`gold = 100`, `name = Aria`, `print(name, gold)`],
        badLine: 1,
        hint: "Aria isn't defined — it should be a string." },
    ],
  },

  {
    id: 2,
    title: "The Crossroads",
    topic: "Conditionals (if / elif / else)",
    sigil: "fork",
    teach: [
      "`if` runs a block when its condition is True. `elif` chains more checks; `else` catches the rest.",
      "Comparisons: `==` `!=` `<` `>` `<=` `>=`. Combine with `and` `or` `not`.",
      "Indentation defines the block — Python is strict about it.",
    ],
    example: `hp = 12\nif hp <= 0:\n    print(\"defeated\")\nelif hp < 15:\n    print(\"wounded\")\nelse:\n    print(\"steady\")`,
    xp: 35, mana: 8,
    puzzles: [
      { id: "c-mcq-1", kind: "mcq",
        prompt: "Which keyword runs ONLY when no prior branch matched?",
        options: ["elif", "else", "endif", "default"],
        answer: 1,
        hint: "It's the catch-all at the bottom." },
      { id: "c-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `n = 10\nif n > 5 and n < 20:\n    print(\"mid\")\nelif n > 0:\n    print(\"small\")\nelse:\n    print(\"none\")`,
        answer: "mid",
        hint: "10 is between 5 and 20." },
      { id: "c-fill-1", kind: "fill",
        prompt: "Fill the blank so a number is `even` only when divisible by 2.",
        code: `n = 14\nif n ___ 2 == 0:\n    print(\"even\")`,
        blanks: ["%"],
        accept: [["%"]],
        hint: "Modulo returns the remainder." },
      { id: "c-drag-1", kind: "drag",
        prompt: "Arrange the lines into a working fizz-check (prints 'fizz' if divisible by 3).",
        shuffled: [`    print(\"fizz\")`, `n = 9`, `if n % 3 == 0:`],
        ordered: [`n = 9`, `if n % 3 == 0:`, `    print(\"fizz\")`],
        hint: "Variable first, then the test, then the indented body." },
    ],
  },

  {
    id: 3,
    title: "The Endless Stair",
    topic: "Loops (for / while)",
    sigil: "stair",
    teach: [
      "`for x in iterable:` walks each item. `range(n)` yields 0..n-1.",
      "`while cond:` repeats until the condition turns False. Beware infinite loops.",
      "`break` quits the loop; `continue` skips to the next iteration.",
    ],
    example: `total = 0\nfor i in range(4):\n    total += i\nprint(total)  # 0+1+2+3 = 6`,
    xp: 40, mana: 10,
    puzzles: [
      { id: "l-d3-1", kind: "d3", visual: "loop-tracer",
        prompt: "Watch the loop tick through. What is `total` at the end?",
        code: `total = 0\nfor i in range(5):\n    total += i`,
        traceVar: "total",
        answer: "10",
        hint: "0+1+2+3+4." },
      { id: "l-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `for i in range(3):\n    if i == 1:\n        continue\n    print(i)`,
        answer: "0\n2",
        accept: ["0\n2", "0 2", "02"],
        hint: "`continue` skips printing for that iteration." },
      { id: "l-fill-1", kind: "fill",
        prompt: "Sum only EVEN numbers from 1 to 10.",
        code: `total = 0\nfor n in range(1, 11):\n    if n ___ 2 == 0:\n        total += n\nprint(total)  # 30`,
        blanks: ["%"],
        accept: [["%"]],
        hint: "Modulo again — even means remainder 0 when divided by 2." },
      { id: "l-bug-1", kind: "bug",
        prompt: "This loop will never end. Click the bad line.",
        lines: [`x = 0`, `while x < 5:`, `    print(x)`, `    x = x`],
        badLine: 3,
        hint: "x must change toward the exit condition." },
    ],
  },

  {
    id: 4,
    title: "The Hoarder's Vault",
    topic: "Lists & Dictionaries",
    sigil: "chest",
    teach: [
      "Lists are ordered: `inv = [\"sword\", \"potion\"]`. Index with `inv[0]`.",
      "Dicts map keys → values: `stats = {\"hp\": 20}`. Access with `stats[\"hp\"]`.",
      "Lists: `.append()`, `.pop()`, slicing `inv[1:3]`. Dicts: `.get(k, default)`, `.keys()`, `.values()`.",
    ],
    example: `inv = [\"sword\", \"potion\"]\ninv.append(\"key\")\nprint(inv[-1])  # 'key'`,
    xp: 45, mana: 10,
    puzzles: [
      { id: "d-d3-1", kind: "d3", visual: "list-tracer",
        prompt: "After running, what does `inv` contain (as a list)?",
        code: `inv = [\"sword\", \"potion\", \"map\"]\ninv.append(\"key\")\ninv.pop(0)`,
        finalState: ["potion", "map", "key"],
        answer: "['potion', 'map', 'key']",
        accept: ["['potion', 'map', 'key']", "[potion, map, key]", "potion, map, key"],
        hint: "append adds at the end; pop(0) removes the first." },
      { id: "d-mcq-1", kind: "mcq",
        prompt: "How do you safely fetch `stats[\"mp\"]` defaulting to 0 if missing?",
        options: ["stats[\"mp\"] or 0", "stats.get(\"mp\", 0)", "stats.fetch(\"mp\", 0)", "default(stats, \"mp\", 0)"],
        answer: 1,
        hint: "Dict's `.get` takes a default value." },
      { id: "d-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `nums = [1, 2, 3, 4]\nprint(nums[1:3])`,
        answer: "[2, 3]",
        accept: ["[2, 3]", "[2,3]"],
        hint: "Slicing is `[start:stop]`, stop excluded." },
      { id: "d-fill-1", kind: "fill",
        prompt: "Add `\"hp\": 100` to the dict.",
        code: `stats = {}\nstats[___] = 100\nprint(stats)`,
        blanks: ["\"hp\""],
        accept: [["\"hp\"", "'hp'"]],
        hint: "Keys are usually strings — wrap in quotes." },
    ],
  },

  {
    id: 5,
    title: "The Spell Tome",
    topic: "Functions",
    sigil: "tome",
    teach: [
      "Define with `def name(params):` — body is indented; `return` sends a value back.",
      "Default args: `def greet(who=\"world\")`. Keyword args at call site: `greet(who=\"Aria\")`.",
      "Functions are values — you can pass them around like any other object.",
    ],
    example: `def add(a, b=1):\n    return a + b\nprint(add(5))      # 6\nprint(add(5, b=10)) # 15`,
    xp: 50, mana: 12,
    puzzles: [
      { id: "f-fill-1", kind: "fill",
        prompt: "Complete this function so it returns the doubled value.",
        code: `def double(n):\n    ___ n * 2\nprint(double(7))  # 14`,
        blanks: ["return"],
        accept: [["return"]],
        hint: "How does a function send a value back?" },
      { id: "f-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `def power(base, exp=2):\n    return base ** exp\nprint(power(3))`,
        answer: "9",
        hint: "exp defaulted to 2." },
      { id: "f-mcq-1", kind: "mcq",
        prompt: "What does this function `print`?",
        code: `def f(x): return x + 1\nprint(f(f(2)))`,
        options: ["3", "4", "5", "Error"],
        answer: 1,
        hint: "f(2)=3, then f(3)=4." },
      { id: "f-drag-1", kind: "drag",
        prompt: "Assemble a function `area` that returns w*h, then call it.",
        shuffled: [`print(area(3, 4))`, `def area(w, h):`, `    return w * h`],
        ordered: [`def area(w, h):`, `    return w * h`, `print(area(3, 4))`],
        hint: "Define before calling." },
    ],
  },

  {
    id: 6,
    title: "The Alchemist's Press",
    topic: "List Comprehensions",
    sigil: "flask",
    teach: [
      "`[expr for x in iterable]` builds a list in one line.",
      "Add a filter: `[x for x in nums if x > 0]`.",
      "Set & dict comps too: `{x*x for x in nums}` and `{k: v for k, v in pairs}`.",
    ],
    example: `squares = [n*n for n in range(5)]\nprint(squares)  # [0, 1, 4, 9, 16]`,
    xp: 55, mana: 12,
    puzzles: [
      { id: "lc-fill-1", kind: "fill",
        prompt: "Build a list of cubes from 1 to 5.",
        code: `cubes = [n ___ for n in range(1, 6)]\nprint(cubes)  # [1, 8, 27, 64, 125]`,
        blanks: ["**3"],
        accept: [["**3", "** 3"]],
        hint: "Cube means power of 3." },
      { id: "lc-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `nums = [1, 2, 3, 4, 5]\nprint([x for x in nums if x % 2])`,
        answer: "[1, 3, 5]",
        accept: ["[1, 3, 5]", "[1,3,5]"],
        hint: "`x % 2` is truthy for odd numbers." },
      { id: "lc-mcq-1", kind: "mcq",
        prompt: "Which builds a dict of word→length?",
        options: [
          "{w: len(w) for w in words}",
          "[w: len(w) for w in words]",
          "(w, len(w) for w in words)",
          "dict[w, len(w) for w in words]",
        ],
        answer: 0,
        hint: "Dict comp uses `{key: value for ...}`." },
      { id: "lc-bug-1", kind: "bug",
        prompt: "This should give `[2, 4, 6]`. Click the bad line.",
        lines: [`nums = [1, 2, 3]`, `doubled = [n * 2 in nums]`, `print(doubled)`],
        badLine: 1,
        hint: "Comprehension needs `for` before `in`." },
    ],
  },

  {
    id: 7,
    title: "The Tusked Sage",
    topic: "Walrus Operator (:=)",
    sigil: "tusk",
    teach: [
      "`:=` assigns AND yields the value, all inside an expression. Hence the tusks.",
      "Useful in `while` and `if` to avoid computing twice or repeating reads.",
      "Available in Python 3.8+. Use sparingly — readability matters.",
    ],
    example: `nums = [1, 2, 3, 4, 5]\nif (n := len(nums)) > 3:\n    print(f\"long: {n}\")  # long: 5`,
    xp: 60, mana: 14,
    puzzles: [
      { id: "w-mcq-1", kind: "mcq",
        prompt: "What does `:=` do that `=` cannot?",
        options: [
          "Assigns AND returns the value as part of an expression",
          "Compares two values for equality",
          "Defines a constant",
          "Imports a module",
        ],
        answer: 0,
        hint: "Look at the example — the assignment lives INSIDE the `if` condition." },
      { id: "w-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `data = [10, 20, 30]\nif (total := sum(data)) > 50:\n    print(total)`,
        answer: "60",
        hint: "sum is 60, greater than 50, then printed." },
      { id: "w-fill-1", kind: "fill",
        prompt: "Use the walrus to read input ONCE inside a while.",
        code: `# pretend get_line() returns 'STOP' eventually\nwhile (line ___ get_line()) != 'STOP':\n    print(line)`,
        blanks: [":="],
        accept: [[":=", ":= "]],
        hint: "Walrus tusks: colon-equals." },
      { id: "w-bug-1", kind: "bug",
        prompt: "Make the walrus work. Click the bad line.",
        lines: [`vals = [1,2,3]`, `if n = len(vals) > 2:`, `    print(n)`],
        badLine: 1,
        hint: "Inside an expression, you need walrus, not regular `=`." },
    ],
  },

  {
    id: 8,
    title: "The Whispering Sigil",
    topic: "Lambdas",
    sigil: "rune",
    teach: [
      "`lambda args: expr` is an anonymous, single-expression function.",
      "Common with `sorted`, `map`, `filter`: `sorted(words, key=lambda w: len(w))`.",
      "If it needs more than one line, use `def`. Lambdas are sigils, not tomes.",
    ],
    example: `square = lambda x: x*x\nprint(square(6))  # 36`,
    xp: 60, mana: 14,
    puzzles: [
      { id: "la-mcq-1", kind: "mcq",
        prompt: "Which is a valid lambda that adds two numbers?",
        options: [
          "lambda a, b: return a + b",
          "lambda a, b: a + b",
          "lambda(a, b) => a + b",
          "def lambda a, b: a + b",
        ],
        answer: 1,
        hint: "No `return`, no parens around args." },
      { id: "la-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `words = [\"book\", \"a\", \"hi\"]\nwords.sort(key=lambda w: len(w))\nprint(words)`,
        answer: "['a', 'hi', 'book']",
        accept: ["['a', 'hi', 'book']", "[a, hi, book]"],
        hint: "Sorts by ascending length." },
      { id: "la-fill-1", kind: "fill",
        prompt: "Use a lambda with `map` to triple each value.",
        code: `nums = [1, 2, 3]\ntripled = list(map(___, nums))\nprint(tripled)  # [3, 6, 9]`,
        blanks: ["lambda x: x*3"],
        accept: [["lambda x: x*3", "lambda x:x*3", "lambda n: n*3", "lambda x: 3*x"]],
        hint: "Format: `lambda PARAM: EXPR`." },
      { id: "la-drag-1", kind: "drag",
        prompt: "Assemble: filter only positives from `nums`.",
        shuffled: [`print(list(positives))`, `nums = [-1, 4, -3, 7]`, `positives = filter(lambda n: n > 0, nums)`],
        ordered: [`nums = [-1, 4, -3, 7]`, `positives = filter(lambda n: n > 0, nums)`, `print(list(positives))`],
        hint: "Define data → filter → print." },
    ],
  },

  {
    id: 9,
    title: "The Yielding Loom",
    topic: "Generators / yield",
    sigil: "loom",
    teach: [
      "`yield` turns a function into a generator — values are produced lazily, one at a time.",
      "Generators don't compute until iterated; they pause and resume their state.",
      "Great for streams, infinite sequences, and saving memory.",
    ],
    example: `def counter():\n    n = 0\n    while True:\n        yield n\n        n += 1\ng = counter()\nprint(next(g), next(g), next(g))  # 0 1 2`,
    xp: 70, mana: 16,
    puzzles: [
      { id: "g-mcq-1", kind: "mcq",
        prompt: "What is the key difference between `yield` and `return`?",
        options: [
          "`yield` raises an error if reached twice",
          "`yield` pauses the function, preserving state to resume on next iteration",
          "`return` works in loops, `yield` does not",
          "There is none — they are aliases",
        ],
        answer: 1,
        hint: "Generators remember where they left off." },
      { id: "g-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `def evens(n):\n    for i in range(n):\n        if i % 2 == 0:\n            yield i\nprint(list(evens(6)))`,
        answer: "[0, 2, 4]",
        accept: ["[0, 2, 4]", "[0,2,4]"],
        hint: "0..5, keep evens." },
      { id: "g-fill-1", kind: "fill",
        prompt: "Make this a generator that emits 1, 2, 3.",
        code: `def trio():\n    for i in range(1, 4):\n        ___ i\nprint(list(trio()))`,
        blanks: ["yield"],
        accept: [["yield"]],
        hint: "The keyword that pauses and produces." },
      { id: "g-bug-1", kind: "bug",
        prompt: "This should iterate twice and stop. Click the bad line.",
        lines: [`def two():`, `    yield 1`, `    return 2`, `print(list(two()))`],
        badLine: 2,
        hint: "Inside a generator, plain `return X` doesn't yield X — it just stops the generator." },
    ],
  },

  {
    id: 10,
    title: "The Forge of Forms",
    topic: "Classes & OOP",
    sigil: "anvil",
    teach: [
      "`class Name:` defines a blueprint. `__init__(self, ...)` is the constructor.",
      "Attributes live on `self`. Methods are functions defined inside the class.",
      "Create instances with `Name(args)`.",
    ],
    example: `class Hero:\n    def __init__(self, name):\n        self.name = name\n    def greet(self):\n        return f\"Hail, {self.name}\"\nh = Hero(\"Aria\")\nprint(h.greet())`,
    xp: 80, mana: 18,
    puzzles: [
      { id: "o-fill-1", kind: "fill",
        prompt: "Complete the constructor.",
        code: `class Potion:\n    def __init__(___, power):\n        self.power = power\np = Potion(50)\nprint(p.power)`,
        blanks: ["self"],
        accept: [["self"]],
        hint: "First param of every method." },
      { id: "o-mcq-1", kind: "mcq",
        prompt: "What is `self`?",
        options: [
          "A reserved Python keyword",
          "A reference to the current instance",
          "Always equal to the class",
          "An import",
        ],
        answer: 1,
        hint: "It's the instance the method was called on." },
      { id: "o-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `class C:\n    n = 0\n    def __init__(self):\n        C.n += 1\nC(); C(); C()\nprint(C.n)`,
        answer: "3",
        hint: "Constructor bumps the class attribute each time." },
      { id: "o-d3-1", kind: "d3", visual: "class-tree",
        prompt: "Given the diagram, which method does `Sword` define directly?",
        nodes: [
          {id: "Item", parent: null, methods: ["__init__", "describe"]},
          {id: "Weapon", parent: "Item", methods: ["attack"]},
          {id: "Sword", parent: "Weapon", methods: ["sharpen"]},
        ],
        options: ["describe", "attack", "sharpen", "__init__"],
        answer: 2,
        hint: "Look at the leaf node." },
    ],
  },

  {
    id: 11,
    title: "The Bloodlines",
    topic: "Inheritance & Polymorphism",
    sigil: "tree",
    teach: [
      "`class Child(Parent):` inherits everything from Parent, then adds or overrides.",
      "`super().__init__(...)` calls the parent constructor.",
      "Polymorphism: same method name, different classes can implement it differently.",
    ],
    example: `class Animal:\n    def speak(self): return \"...\"\nclass Dog(Animal):\n    def speak(self): return \"woof\"\nprint(Dog().speak())`,
    xp: 85, mana: 18,
    puzzles: [
      { id: "i-d3-1", kind: "d3", visual: "class-tree",
        prompt: "If you call `Wizard().cast()`, where does Python find it?",
        nodes: [
          {id: "Being", parent: null, methods: ["live"]},
          {id: "Caster", parent: "Being", methods: ["cast"]},
          {id: "Wizard", parent: "Caster", methods: []},
        ],
        options: ["Being", "Caster", "Wizard", "Nowhere"],
        answer: 1,
        hint: "Walk up the tree until you find a definition." },
      { id: "i-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `class A:\n    def kind(self): return \"A\"\nclass B(A):\n    def kind(self): return \"B\"\nfor x in [A(), B(), A()]:\n    print(x.kind(), end=\" \")`,
        answer: "A B A",
        accept: ["A B A", "ABA", "A B A "],
        hint: "Each instance picks its OWN class's method." },
      { id: "i-fill-1", kind: "fill",
        prompt: "Call the parent constructor inside the child.",
        code: `class Item:\n    def __init__(self, name):\n        self.name = name\nclass Sword(Item):\n    def __init__(self, name, dmg):\n        ___().__init__(name)\n        self.dmg = dmg\nprint(Sword(\"Edge\", 10).name)`,
        blanks: ["super"],
        accept: [["super"]],
        hint: "Built-in for parent reference." },
      { id: "i-mcq-1", kind: "mcq",
        prompt: "Polymorphism means…",
        options: [
          "A function that takes many parameters",
          "Many forms — different classes responding to the same method name",
          "Multiple inheritance only",
          "Renaming a class",
        ],
        answer: 1,
        hint: "Greek: poly = many, morph = form." },
    ],
  },

  {
    id: 12,
    title: "The Wreathed Glyph",
    topic: "Decorators",
    sigil: "wreath",
    teach: [
      "A decorator is a function that takes a function and returns a (usually wrapped) function.",
      "Syntax: `@deco` above a `def` is sugar for `f = deco(f)`.",
      "Use them to add logging, timing, caching, auth — without touching the original body.",
    ],
    example: `def shout(f):\n    def wrap(*a, **kw):\n        return f(*a, **kw).upper()\n    return wrap\n\n@shout\ndef greet(name):\n    return f\"hi {name}\"\nprint(greet(\"aria\"))  # HI ARIA`,
    xp: 95, mana: 20,
    puzzles: [
      { id: "de-mcq-1", kind: "mcq",
        prompt: "`@deco` above a function definition is equivalent to:",
        options: ["f = f(deco)", "f = deco(f)", "deco(f) = f", "f.deco()"],
        answer: 1,
        hint: "Decorator wraps the function." },
      { id: "de-pred-1", kind: "predict",
        prompt: "What prints?",
        code: `def double(f):\n    def wrap(x):\n        return f(x) * 2\n    return wrap\n\n@double\ndef inc(x):\n    return x + 1\nprint(inc(3))`,
        answer: "8",
        hint: "inc(3) = 4, doubled = 8." },
      { id: "de-fill-1", kind: "fill",
        prompt: "Apply the existing `cache` decorator to `slow`.",
        code: `def cache(f):\n    seen = {}\n    def wrap(x):\n        if x not in seen:\n            seen[x] = f(x)\n        return seen[x]\n    return wrap\n\n___\ndef slow(n):\n    return n * n`,
        blanks: ["@cache"],
        accept: [["@cache"]],
        hint: "Decorator syntax begins with @." },
      { id: "de-drag-1", kind: "drag",
        prompt: "Assemble a logger decorator and apply it.",
        shuffled: [
          `    return wrap`,
          `def log(f):`,
          `@log`,
          `def wrap(*a):`,
          `    print(\"calling\", f.__name__)`,
          `    return f(*a)`,
          `def hello(): return \"hi\"`,
        ],
        ordered: [
          `def log(f):`,
          `    def wrap(*a):`,
          `        print(\"calling\", f.__name__)`,
          `        return f(*a)`,
          `    return wrap`,
          `@log`,
          `def hello(): return \"hi\"`,
        ],
        // NOTE: drag puzzle just checks order match — indentation is part of the line text.
        // We accept either with or without inner-indented body for the wrap function lines.
        // The simpler version below is what's checked:
        simpleOrdered: [
          `def log(f):`,
          `    def wrap(*a):`,
          `    print(\"calling\", f.__name__)`,
          `    return f(*a)`,
          `    return wrap`,
          `@log`,
          `def hello(): return \"hi\"`,
        ],
        hint: "Outer first, inner wrap, return wrap, then @log on hello." },
    ],
  },

  {
    id: 13,
    title: "The Time-Tides",
    topic: "Async / Await",
    sigil: "tide",
    teach: [
      "`async def` declares a coroutine. `await` pauses it until another coroutine resolves.",
      "Coroutines don't run themselves — `asyncio.run(main())` (or a running loop) does.",
      "Concurrency, not parallelism: while one task awaits I/O, others can run.",
    ],
    example: `import asyncio\nasync def hi():\n    await asyncio.sleep(0)\n    return \"hi\"\nprint(asyncio.run(hi()))`,
    xp: 110, mana: 22,
    puzzles: [
      { id: "a-mcq-1", kind: "mcq",
        prompt: "Calling `hi()` from `async def hi()` returns…",
        options: ["The string \"hi\"", "A coroutine object", "None", "An error"],
        answer: 1,
        hint: "It's not run until awaited or scheduled." },
      { id: "a-fill-1", kind: "fill",
        prompt: "Pause until `fetch()` resolves.",
        code: `async def main():\n    data = ___ fetch()\n    return data`,
        blanks: ["await"],
        accept: [["await"]],
        hint: "The keyword that pauses a coroutine." },
      { id: "a-pred-1", kind: "predict",
        prompt: "What prints (rough order — it's deterministic here)?",
        code: `import asyncio\nasync def task(n):\n    await asyncio.sleep(0)\n    print(n)\nasync def main():\n    await asyncio.gather(task(1), task(2), task(3))\nasyncio.run(main())`,
        answer: "1\n2\n3",
        accept: ["1\n2\n3", "1 2 3", "123"],
        hint: "Same-priority sleeps, scheduled in order." },
      { id: "a-mcq-2", kind: "mcq",
        prompt: "Which best describes `asyncio.gather`?",
        options: [
          "Runs coroutines sequentially",
          "Runs coroutines concurrently and waits for all to finish",
          "Cancels all running coroutines",
          "Converts a coroutine to a thread",
        ],
        answer: 1,
        hint: "Gather all the awaitables and wait." },
    ],
  },
];

window.PYQUEST_LEVELS = LEVELS;
